---
title: "LSKVC Return to Play (Indoor) Logistics Considerations"
author: "Nicolas Vecchione (Powerball Rep)"
date: "`r format(Sys.time(), '%d/%m/%Y')`"
output: 
  pdf_document:
    toc: true
    toc_depth: 2
    number_sections: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Motivation {-}

This document aims to support LSKVC in their organisation and running of official LSKVC indoor volleyball sessions returning from the COVID19 hiatus. Its overarching aim is to provide means to reduce the risks of virus propagation, protecting our members and the general population and create the start of a sustainable way to play volleyball during the ongoing pandemic. 

The **Logistics Considerations** contains considerations for us to decide on how we can plan to run the session, volunteers required, etc. 

This document should be read alongside the **Club Requirements**, **Players Rules** and **Risk Assessment** documents. 

The **Risk Assessment** (available at  *[https://github.com/cuisquare/ReturnToVolleyball/blob/master/IndoorTraining/LSKVC_IndoorTraining_RiskAssessment.pdf](https://github.com/cuisquare/ReturnToVolleyball/blob/master/IndoorTraining/LSKVC_IndoorTraining_RiskAssessment.pdf)*) must be read and understood alongside this document as the basis for it.

The **Players Rules** (available at *[https://github.com/cuisquare/ReturnToVolleyball/blob/master/IndoorTraining/LSKVC_IndoorTraining_PlayersRules.pdf](https://github.com/cuisquare/ReturnToVolleyball/blob/master/IndoorTraining/LSKVC_IndoorTraining_PlayersRules.pdf)*) should be read and understood alongside those requirements to understand what will be expected from players in a club run session.

The **Club Requirements** (available at  *[https://github.com/cuisquare/ReturnToVolleyball/blob/master/IndoorTraining/LSKVC_IndoorTraining_ClubRequirements.pdf](https://github.com/cuisquare/ReturnToVolleyball/blob/master/IndoorTraining/LSKVC_IndoorTraining_ClubRequirements.pdf)*) should also be read to be aware of the level of support you can expect during a session.

\newpage
# Logistics Considerations

## General considerations

The number of users is capped at 17 total based on volleyball england guidance and this includes any organiser (covid officer as minimum + coach for coached session).

## Session possible Configurations

To be completed.
